/*
 * MTIMERS_config.h
 *
 *  Created on: Jan 14, 2024
 *      Author: Mina
 */

#ifndef MCAL_03_TIMERS_MTIMERS_CONFIG_H_
#define MCAL_03_TIMERS_MTIMERS_CONFIG_H_

/*
 *  CONFIGRATION OPTIONS
 *  1-MTIMER_ENABLE
 *  2-MTIMER_DISABLE
 */
#define MTIMER_TIMER0    MTIMER_ENABLE
#define MTIMER_TIMER1    MTIMER_DISABLE
#define MTIMER_TIMER2    MTIMER_DISABLE


/*
 *  WAVEFORM GENERATION MODE FOR TIMER0 OPTIONS
 *
 *  1-TIMER0_WAVEFORM_GENERATION_MODE_NORMAL_MODE
 *  2- TIMER0_WAVEFORM_GENERATION_MODE_PHASE_CORRECT_MODE
 *  3-TIMER0_WAVEFORM_GENERATION_MODE_CTC_MODE
 *  4-TIMER0_WAVEFORM_GENERATION_MODE_FPWM_MODE
 *
 */
#define TIMER0_WAVEFORM_GENERATION_MODE       TIMER0_WAVEFORM_GENERATION_MODE_PHASE_CORRECT_MODE

/*
 * COMPARE MATCH OUTPUT MODE AT NORMAL MODE FOR TIMER0 OPTIONS
 *
 * 1-TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0
 * 2-TIMER0_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC0
 * 3-TIMER0_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC0
 * 4-TIMER0_COMPARE_MATCH_OUTPUT_MODE_SET_OC0
 */

#define TIMER0_COMPARE_MATCH_OUTPUT_MODE_NORMAL_MODE          TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0

/*
 * COMPARE MATCH OUTPUT MODE AT CTC MODE FOR TIMER0 OPTIONS
 *
 * 1-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0
 * 2-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC0
 * 3-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC0
 * 4-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_SET_OC0
 */

#define TIMER0_COMPARE_MATCH_OUTPUT_MODE_CTC_MODE          TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0



/*
 * COMPARE MATCH OUTPUT MODE AT PAHSE COREECT MODE FOR TIMER0 OPTIONS
 *
 * 1-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0
 * 2-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_NON_INVERTING_ON_OC0
 * 3-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_INVERTING_ON_OC0
 */

#define TIMER0_COMPARE_MATCH_OUTPUT_MODE_PHASE_CORRECT_MODE             TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_INVERTING_ON_OC0

/*
 * COMPARE MATCH OUTPUT MODE AT FAST PWM MODE FOR TIMER0 OPTIONS
 *
 * 1-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0
 * 2-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_NON_INVERTING_ON_OC0
 * 3-TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_INVERTING_ON_OC0
 */

#define TIMER0_COMPARE_MATCH_OUTPUT_MODE_FAST_PWM_MODE       TCCR0_TIMER0_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC0
/***************************************************Configration for TIMER1*************************************************/
/*
 *  WAVEFORM GENERATION MODE FOR TIMER1 OPTIONS
 *
 *  1- TIMER1_WAVEFORM_GENERATION_MODE_NORMAL_MODE
 *  2- TIMER1_WAVEFORM_GENERATION_MODE_PWM_8BIT_MODE
 *  3- TIMER1_WAVEFORM_GENERATION_MODE_PWM_9BIT_MODE
 *  4- TIMER1_WAVEFORM_GENERATION_MODE_PWM_10BIT_MODE
 *  5- TIMER1_WAVEFORM_GENERATION_MODE_CTC_MODE_OCR1A
 *  6- TIMER1_WAVEFORM_GENERATION_MODE_FPWM_8BIT_MODE
 *  7- TIMER1_WAVEFORM_GENERATION_MODE_FPWM_9BIT_MODE
 *  8- TIMER1_WAVEFORM_GENERATION_MODE_FPWM_10BIT_MODE
 *  9- TIMER1_WAVEFORM_GENERATION_MODE_PWM_PHASE_FREQ_CORRECT_ICR1
 *  10-TIMER1_WAVEFORM_GENERATION_MODE_PWM_PHASE_FREQ_CORRECT_OCR1A
 *  11-TIMER1_WAVEFORM_GENERATION_MODE_PWM_PHASE_CORRECT_ICR1
 *  12-TIMER1_WAVEFORM_GENERATION_MODE_PWM_PHASE_CORRECT_OCR1A
 *  13-TIMER1_WAVEFORM_GENERATION_MODE_CTC_MODE_ICR1
 *  14-TIMER1_WAVEFORM_GENERATION_MODE_FPWM_MODE_ICR1
 *  15-TIMER1_WAVEFORM_GENERATION_MODE_FPWM_MODE_OCR1A
 *
 */
#define TIMER1_WAVEFORM_GENERATION_MODE      TIMER1_WAVEFORM_GENERATION_MODE_FPWM_MODE_OCR1A

/*
 * PWM MODE For TIMER1 OPTIONS
 *
 * 1-TIMER1_FAST_PWM_MODE
 * 2-TIMER1_PHASE_CORRECT_MODE
 */
#define TIMER1_PWM_MODE                      TIMER1_FAST_PWM_MODE
/*
 * COMPARE MATCH OUTPUT MODE AT NORMAL MODE FOR TIMER1 OPTIONS
 *
 * 1-TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A
 * 2-TIMER1_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC1A
 * 3-TIMER1_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC1A
 * 4-TIMER1_COMPARE_MATCH_OUTPUT_MODE_SET_OC1A
 */
#define TIMER1_COMPARE_MATCH_OUTPUT_MODE_NORMAL_MODE          TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A

/*
 * COMPARE MATCH OUTPUT MODE AT CTC MODE FOR TIMER1 OPTIONS
 *
 * 1-TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A
 * 2-TIMER1_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC1A
 * 3-TIMER1_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC1A
 * 4-TIMER1_COMPARE_MATCH_OUTPUT_MODE_SET_OC1A
 */
#define TIMER1_COMPARE_MATCH_OUTPUT_MODE_CTC_MODE          TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A

/*
 * COMPARE MATCH OUTPUT MODE AT PAHSE CORRECT PWM MODE FOR TIMER1 OPTIONS
 *
 * 1-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A
 * 2-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_ON_UP_COUNTING_OC1A
 * 3-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_CLEAR_ON_UP_COUNTING_OC1A
 * 4-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_SET_ON_UP_COUNTING_OC1A
 */
#define TIMER1_COMPARE_MATCH_OUTPUT_MODE_PHASE_CORRECT_MODE             TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A

/*
 * COMPARE MATCH OUTPUT MODE AT FAST PWM MODE FOR TIMER1 OPTIONS
 *
 * 1-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC1A
 * 2-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC1A
 * 3-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC1A
 * 4-TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_SET_OC1A
 */
#define TIMER1_COMPARE_MATCH_OUTPUT_MODE_FAST_PWM_MODE        TCCR1A_TIMER1_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC1A
/***************************************************Configration for TIMER2*************************************************/
/*
 *  WAVEFORM GENERATION MODE FOR TIMER2 OPTIONS
 *
 *  1-TIMER2_WAVEFORM_GENERATION_MODE_NORMAL_MODE
 *  2-TIMER2_WAVEFORM_GENERATION_MODE_PWM_MODE
 *  3-TIMER2_WAVEFORM_GENERATION_MODE_CTC_MODE
 *  4-TIMER2_WAVEFORM_GENERATION_MODE_FPWM_MODE
 *
 */
#define TIMER2_WAVEFORM_GENERATION_MODE      TIMER2_WAVEFORM_GENERATION_MODE_NORMAL_MODE

/*
 * COMPARE MATCH OUTPUT MODE AT NORMAL MODE FOR TIMER2 OPTIONS
 *
 * 1-TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2
 * 2-TIMER2_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC2
 * 3-TIMER2_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC2
 * 4-TIMER2_COMPARE_MATCH_OUTPUT_MODE_SET_OC2
 */

#define TIMER2_COMPARE_MATCH_OUTPUT_MODE_NORMAL_MODE          TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2

/*
 * COMPARE MATCH OUTPUT MODE AT CTC MODE FOR TIMER2 OPTIONS
 *
 * 1-TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2
 * 2-TIMER2_COMPARE_MATCH_OUTPUT_MODE_TOGGLE_OC2
 * 3-TIMER2_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC2
 * 4-TIMER2_COMPARE_MATCH_OUTPUT_MODE_SET_OC2
 */

#define TIMER2_COMPARE_MATCH_OUTPUT_MODE_CTC_MODE          TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2



/*
 * COMPARE MATCH OUTPUT MODE AT PWM MODE FOR TIMER0 OPTIONS
 *
 * 1-TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2
 * 2-TIMER2_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC2
 * 3-TIMER2_COMPARE_MATCH_OUTPUT_MODE_SET_OC2
 */

#define TIMER2_COMPARE_MATCH_OUTPUT_MODE_PWM_MODE             TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2

/*
 * COMPARE MATCH OUTPUT MODE AT FAST PWM MODE FOR TIMER2 OPTIONS
 *
 * 1-TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2
 * 2-TIMER2_COMPARE_MATCH_OUTPUT_MODE_CLEAR_OC2
 * 3-TIMER2_COMPARE_MATCH_OUTPUT_MODE_SET_OC2
 */

#define TIMER2_COMPARE_MATCH_OUTPUT_MODE_FAST_PWM_MODE        TIMER2_COMPARE_MATCH_OUTPUT_MODE_DISCONNCTED_OC2










































/*
 * TIMER0 CLOCK SELECT OPTIONS
 *
 * 1-TIMER0_CLOCK_SELECT_NOPRESCALING
 * 2-TIMER0_CLOCK_SELECT_PRESCALLER_OVER_8
 * 3-TIMER0_CLOCK_SELECT_PRESCALLER_OVER_64
 * 4-TIMER0_CLOCK_SELECT_PRESCALLER_OVER_256
 * 5-TIMER0_CLOCK_SELECT_PRESCALLER_OVER_1024
 * 6-TIMER0_CLOCK_SELECT_CLOCK_ON_FALLINGEDGE
 * 7-TIMER0_CLOCK_SELECT_CLOCK_ON_RISINGEDGE
 */

#define TIMER0_CLOCK_SELECT               TIMER0_CLOCK_SELECT_NOPRESCALING



#endif /* MCAL_03_TIMERS_MTIMERS_CONFIG_H_ */




